### ISSUE TITLE
[Question] 此插件和PowerNukkit的兼容性？

### ISSUE THREAD

**Issue by Eden7Ba23** [WetABQ/EasyAPI-Nukkit#30]
本人在``` Nukkit 1.4.0.0-PN (git-4f0f314) 版本 "PowerNukkit"  (API 1.0.12) ```上运行插件时，出现大量NoClassDefFoundError,指向```top.wetabq.easyapi.api.defaults.PermissionGroupAPI```
以下为PowerNukkit的BugReport：
```
java.lang.NoClassDefFoundError: Could not initialize class top.wetabq.easyapi.api.defaults.PermissionGroupAPI
        at top.wetabq.easyapi.module.defaults.ChatNameTagFormatModule$moduleRegister$nameTagFormatter$1.format(ChatNameTagFormatModule.kt:69)
        at top.wetabq.easyapi.module.defaults.ChatNameTagFormatModule$moduleRegister$nameTagFormatter$1.format(ChatNameTagFormatModule.kt:60)
        at top.wetabq.easyapi.api.defaults.MessageFormatter$DefaultImpls.parseFormat(MessageFormatAPI.kt:58)
        at top.wetabq.easyapi.module.defaults.ChatNameTagFormatModule$moduleRegister$nameTagFormatter$1.parseFormat(ChatNameTagFormatModule.kt:60)
        at top.wetabq.easyapi.api.defaults.MessageFormatAPI.format(MessageFormatAPI.kt:17)
        at top.wetabq.easyapi.module.defaults.ChatNameTagFormatModule$moduleRegister$1$onJoinEvent$1.invoke(ChatNameTagFormatModule.kt:100)
        at top.wetabq.easyapi.module.defaults.ChatNameTagFormatModule$moduleRegister$1$onJoinEvent$1.invoke(ChatNameTagFormatModule.kt:89)
        at top.wetabq.easyapi.module.defaults.AsyncListenerModuleKt$asyncTaskCallEvent$2.onRun(AsyncListenerModule.kt:29)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:25)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```
这些错误大多都指向KotlinLib，但是KotlinLib已经安装：
```
2021-06-05 11:26:53.440 [main] INFO  - 開啟中... PowerNukkit v1.4.0.0-PN
2021-06-05 11:26:53.549 [main] INFO  - 讀取中... KotlinLib v1.4.31
2021-06-05 11:26:53.567 [main] INFO  - 讀取中... MobPlugin v1.19.0
2021-06-05 11:26:53.574 [main] INFO  - 讀取中... EasyAPI v1.1.12.0
2021-06-05 11:26:53.601 [main] INFO  - 讀取中... ScoreboardPlugin v1.0
2021-06-05 11:26:53.668 [main] INFO  - 讀取中... GameAPI v1.0.0-ALPHA
2021-06-05 11:26:53.672 [main] INFO  - 讀取中... EconomyAPI v2.0.1
2021-06-05 11:26:53.694 [main] INFO  - 讀取中... PlaceholderAPI v1.3.3
2021-06-05 11:26:53.744 [main] INFO  - 讀取中... ChainMining v1.2.0
2021-06-05 11:26:53.753 [main] INFO  - [ChainMining]: §aLanguage: zh_CN loaded !
2021-06-05 11:26:53.775 [main] INFO  - [ChainMining]: §aLanguage: en_US loaded !
2021-06-05 11:26:53.778 [main] INFO  - 讀取中... XiaoOnline v1.1.1
2021-06-05 11:26:53.782 [main] INFO  - 讀取中... LuckPerms v5.3.42
2021-06-05 11:26:54.220 [main] INFO  - 讀取中... FakeInventories v1.0.3
2021-06-05 11:26:54.234 [main] INFO  - 讀取中... PepperShop vPN1.3.2
2021-06-05 11:26:54.237 [main] INFO  - 讀取中... Land v1.5.5
2021-06-05 11:26:54.241 [main] INFO  - 讀取中... BlocklyNukkit v1.2.9.3
```
所以是否该插件无法兼容PowerNukkit导致问题？

**Comment by WetABQ** [comment]
这个应该不是和PowerNukkit的兼容性问题，应该是当初ChatNameTag模块设计的时候没有考虑到没有安装权限组（如Luck Perms）插件服务器的兼容性问题

两种解决方案：
1. 安装 Luck Perms 权限组插件
2. 在配置文件中关闭 ChatNameTag 模块

**Comment by Eden7Ba23** [comment]
> 这个应该不是和PowerNukkit的兼容性问题，应该是当初ChatNameTag模块设计的时候没有考虑到没有安装权限组（如Luck Perms）插件服务器的兼容性问题
> 
> 两种解决方案：
> 
>     1. 安装 Luck Perms 权限组插件
> 
>     2. 在配置文件中关闭 ChatNameTag 模块

我觉得问题并不在权限组插件上：
```
2021-06-05 11:26:53.782 [main] INFO  - 讀取中... LuckPerms v5.3.42
```
问题可能出在其他地方。
